# Generated by Django 6.0.1 on 2026-01-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Typo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sportSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.IntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('informations_d_acces_en_transport_en_commun', models.TextField()),
                ('appellation', models.CharField(max_length=200)),
                ('datation', models.CharField(max_length=100)),
                ('periode_de_construction', models.CharField(max_length=100)),
                ('historique_et_description', models.TextField()),
                ('credits', models.CharField(max_length=200)),
                ('url_image', models.URLField()),
                ('adresse_com', models.CharField(max_length=200)),
                ('date_s_de_reference', models.ManyToManyField(blank=True, to='www.datereference')),
                ('denomination', models.ManyToManyField(blank=True, to='www.denomination')),
                ('site_olympique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.site')),
                ('typologie', models.ManyToManyField(blank=True, to='www.typo')),
            ],
        ),
    ]
