# Generated by Django 6.0.1 on 2026-01-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsite',
            name='informations_d_acces_en_transport_en_commun',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sportsite',
            name='site_olympique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='www.site'),
        ),
    ]
