# Generated by Django 6.0 on 2026-01-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_alter_sportsite_site_olympique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsite',
            name='informations_d_acces_en_transport_en_commun',
            field=models.TextField(blank=True, null=True),
        ),
    ]
